const words = [
    { english: "delegate", meanings: ["任せる", "委任する"], examples: ["She delegated the project to her team."], level: "medium" },
    { english: "postpone", meanings: ["延期する", "後回しにする"], examples: ["They postponed the meeting until next Monday."], level: "medium" },
    { english: "innovate", meanings: ["革新する", "新しくする"], examples: ["The company innovated a new method."], level: "hard" },
    { english: "assemble", meanings: ["集める", "組み立てる"], examples: ["We assembled the new desks."], level: "medium" },
    { english: "authorize", meanings: ["許可する", "認可する"], examples: ["The manager authorized the payment."], level: "medium" },
    { english: "revenue", meanings: ["収益", "売上"], examples: ["The company's revenue increased this year."], level: "medium" },
    { english: "accomplish", meanings: ["達成する", "成し遂げる"], examples: ["She accomplished her goal last month."], level: "medium" },
    { english: "specification", meanings: ["仕様", "明細"], examples: ["Please check the product specifications."], level: "medium" },
    { english: "promotion", meanings: ["昇進", "販促活動"], examples: ["She got a promotion after one year."], level: "easy" },
    { english: "affiliate", meanings: ["提携する", "系列会社"], examples: ["Our company affiliates with foreign firms."], level: "hard" },
    { english: "allocate", meanings: ["割り当てる", "配分する"], examples: ["They allocated more budget for marketing."], level: "medium" },
    { english: "shipment", meanings: ["発送", "出荷"], examples: ["The shipment arrived on time."], level: "medium" },
    { english: "negotiation", meanings: ["交渉", "話し合い"], examples: ["The negotiation was successful."], level: "hard" },
    { english: "productivity", meanings: ["生産性", "能率"], examples: ["We need to improve productivity."], level: "medium" },
    { english: "reservation", meanings: ["予約", "取り置き"], examples: ["I made a reservation at the hotel."], level: "easy" },
    { english: "inventory", meanings: ["在庫", "棚卸し"], examples: ["We checked the inventory yesterday."], level: "medium" },
    { english: "vendor", meanings: ["販売業者", "売り手"], examples: ["The vendor delivered the goods."], level: "medium" },
    { english: "contractor", meanings: ["請負業者", "契約者"], examples: ["The contractor started the project."], level: "hard" },
    { english: "attorney", meanings: ["弁護士", "代理人"], examples: ["The attorney reviewed the contract."], level: "medium" },
    { english: "subsidiary", meanings: ["子会社", "支社"], examples: ["This is a subsidiary of a big company."], level: "hard" },
    { english: "merger", meanings: ["合併", "統合"], examples: ["The merger created a stronger company."], level: "hard" },
    { english: "dividend", meanings: ["配当", "利益分配"], examples: ["The company paid a dividend this month."], level: "hard" },
    { english: "acquisition", meanings: ["買収", "取得"], examples: ["The acquisition took six months."], level: "hard" },
    { english: "broker", meanings: ["仲介業者", "ブローカー"], examples: ["The broker helped sell the property."], level: "medium" },
    { english: "compliance", meanings: ["遵守", "適合"], examples: ["Compliance with the rules is important."], level: "hard" },
    { english: "solicitation", meanings: ["勧誘", "要請"], examples: ["They sent a solicitation to the client."], level: "hard" },
    { english: "custody", meanings: ["管理", "保護"], examples: ["The documents are in custody."], level: "medium" },
    { english: "mortgage", meanings: ["住宅ローン", "担保"], examples: ["He applied for a mortgage."], level: "medium" },
    { english: "procurement", meanings: ["調達", "獲得"], examples: ["Procurement of materials was smooth."], level: "hard" },
    { english: "entrepreneur", meanings: ["起業家", "事業家"], examples: ["He is a successful entrepreneur."], level: "medium" },
    { english: "arbitration", meanings: ["仲裁", "調停"], examples: ["The dispute was settled by arbitration."], level: "impossible" },
    { english: "diversify", meanings: ["多様化する", "広げる"], examples: ["The company diversified its products."], level: "hard" },
    { english: "logistics", meanings: ["物流", "流通管理"], examples: ["Logistics is important for e-commerce."], level: "hard" },
    { english: "valuation", meanings: ["評価", "査定"], examples: ["The valuation of the company increased."], level: "hard" },
    { english: "synergy", meanings: ["相乗効果", "共同効果"], examples: ["The synergy between the teams was great."], level: "medium" },
    { english: "audit", meanings: ["監査", "検査"], examples: ["The audit found no problems."], level: "hard" },
    { english: "monetary", meanings: ["金銭の", "財政の"], examples: ["Monetary policy affects the economy."], level: "hard" },
    { english: "deductible", meanings: ["控除可能な"], examples: ["The insurance has a $500 deductible."], level: "hard" },
    { english: "remittance", meanings: ["送金", "送金額"], examples: ["He made a remittance to his family."], level: "medium" },
    { english: "insolvency", meanings: ["支払い不能", "破産状態"], examples: ["The company faced insolvency last year."], level: "impossible" },
    { english: "bankruptcy", meanings: ["破産", "倒産"], examples: ["The company filed for bankruptcy."], level: "hard" },
    { english: "disbursement", meanings: ["支払い", "経費"], examples: ["The disbursement will be made today."], level: "hard" },
    { english: "liquidation", meanings: ["清算", "整理"], examples: ["The company is in liquidation."], level: "impossible" },
    { english: "collateral", meanings: ["担保", "保証"], examples: ["The bank asked for collateral."], level: "hard" },
    { english: "pledge", meanings: ["約束", "誓約"], examples: ["He pledged to complete the project."], level: "medium" },
    { english: "treasury", meanings: ["財務部", "国庫"], examples: ["The treasury controls government funds."], level: "hard" },
    { english: "benchmark", meanings: ["基準", "指標"], examples: ["This is the benchmark for quality."], level: "medium" },
    { english: "maturity", meanings: ["満期", "成熟"], examples: ["The loan will reach maturity next year."], level: "hard" },
    { english: "liability", meanings: ["負債", "責任"], examples: ["The company reduced its liabilities."], level: "medium" },
    { english: "premium", meanings: ["保険料", "割増料金"], examples: ["The premium increased this year."], level: "medium" },
    { english: "exemption", meanings: ["免除", "控除"], examples: ["He received a tax exemption."], level: "medium" },
    { english: "forecast", meanings: ["予測", "見通し"], examples: ["The sales forecast looks good."], level: "medium" },
    { english: "surplus", meanings: ["余剰", "黒字"], examples: ["The company had a budget surplus."], level: "medium" },
    { english: "underwrite", meanings: ["引き受ける", "保証する"], examples: ["The bank underwrote the loan."], level: "hard" },
    { english: "yield", meanings: ["利回り", "収益"], examples: ["The bond has a 3% yield."], level: "medium" },
    { english: "redemption", meanings: ["償還", "救済"], examples: ["The bond is due for redemption."], level: "hard" },
    { english: "appreciation", meanings: ["価値上昇", "感謝"], examples: ["The property showed appreciation."], level: "medium" },
    { english: "devaluation", meanings: ["価値の低下", "通貨切り下げ"], examples: ["The currency suffered devaluation."], level: "hard" },
    { english: "consolidation", meanings: ["統合", "強化"], examples: ["The consolidation improved efficiency."], level: "hard" },
    { english: "resignation", meanings: ["辞職", "辞任"], examples: ["The manager submitted his resignation."], level: "easy" },
    { english: "attendance", meanings: ["出席", "参加"], examples: ["The attendance was very high today."], level: "easy" },
    { english: "predecessor", meanings: ["前任者", "先駆者"], examples: ["He replaced his predecessor last month."], level: "medium" },
    { english: "successor", meanings: ["後継者", "後任"], examples: ["The successor will take office soon."], level: "medium" },
    { english: "assignment", meanings: ["課題", "仕事"], examples: ["I finished my assignment yesterday."], level: "easy" },
    { english: "conference", meanings: ["会議", "協議"], examples: ["The conference starts at 9 a.m."], level: "easy" },
    { english: "contract", meanings: ["契約", "契約書"], examples: ["The contract was signed today."], level: "medium" },
    { english: "clause", meanings: ["条項", "節"], examples: ["Please read the next clause carefully."], level: "hard" },
    { english: "stipulate", meanings: ["規定する", "要求する"], examples: ["The contract stipulates the payment terms."], level: "hard" },
    { english: "terminate", meanings: ["終了する", "打ち切る"], examples: ["They terminated the agreement."], level: "medium" },
    { english: "litigation", meanings: ["訴訟", "裁判"], examples: ["The company faced litigation."], level: "hard" },
    { english: "verdict", meanings: ["評決", "判決"], examples: ["The jury delivered the verdict."], level: "hard" },
    { english: "hearing", meanings: ["公聴会", "審問"], examples: ["The hearing was held yesterday."], level: "medium" },
    { english: "authorize", meanings: ["許可する", "認可する"], examples: ["The manager authorized the payment."], level: "medium" },
    { english: "strategy", meanings: ["戦略", "計画"], examples: ["We need a good strategy."], level: "medium" },
    { english: "audit", meanings: ["監査", "検査"], examples: ["The audit found no issues."], level: "medium" },
    { english: "budget", meanings: ["予算", "経費"], examples: ["We reviewed the budget for next year."], level: "easy" },
    { english: "inventory", meanings: ["在庫", "棚卸し"], examples: ["The inventory was checked yesterday."], level: "medium" },
    { english: "contractor", meanings: ["請負業者", "契約者"], examples: ["The contractor started construction."], level: "hard" },
    { english: "mortgage", meanings: ["住宅ローン", "担保"], examples: ["They paid their mortgage monthly."], level: "medium" },
    { english: "consultant", meanings: ["コンサルタント", "相談役"], examples: ["The consultant advised us on the plan."], level: "medium" },
    { english: "entrepreneur", meanings: ["起業家", "事業家"], examples: ["The entrepreneur launched a new business."], level: "medium" },
    { english: "expenditure", meanings: ["支出", "経費"], examples: ["Expenditure increased this quarter."], level: "medium" },
    { english: "equity", meanings: ["資本", "株式"], examples: ["He invested in equity markets."], level: "hard" },
    { english: "compliance", meanings: ["遵守", "適合"], examples: ["Compliance is important for success."], level: "hard" },
    { english: "subsidiary", meanings: ["子会社", "支社"], examples: ["This is a subsidiary of ABC Corp."], level: "medium" },
    { english: "affiliation", meanings: ["提携", "加盟"], examples: ["Our affiliation strengthened business ties."], level: "hard" },
    { english: "portfolio", meanings: ["資産", "書類入れ"], examples: ["My investment portfolio grew this year."], level: "medium" },
    { english: "restructure", meanings: ["再構築する", "改革する"], examples: ["The company restructured its divisions."], level: "hard" },
    { english: "consolidate", meanings: ["統合する", "強化する"], examples: ["They consolidated their factories."], level: "hard" },
    { english: "arbitrator", meanings: ["仲裁者"], examples: ["The arbitrator settled the dispute."], level: "impossible" },
    { english: "outsource", meanings: ["外部委託する"], examples: ["We outsourced IT support services."], level: "medium" },
    { english: "overhead", meanings: ["間接費", "経費"], examples: ["The company cut its overhead costs."], level: "medium" },
    { english: "amortization", meanings: ["償却", "返済"], examples: ["Amortization schedules were updated."], level: "impossible" },
    { english: "litigate", meanings: ["訴訟を起こす"], examples: ["They decided to litigate over the issue."], level: "hard" },
    { english: "solvency", meanings: ["支払い能力", "財務健全性"], examples: ["The company maintained its solvency."], level: "hard" },
    { english: "vendor", meanings: ["販売業者", "売り手"], examples: ["The vendor delivered the goods."], level: "easy" },
    { english: "insolvency", meanings: ["支払不能", "破産状態"], examples: ["The company faced insolvency issues."], level: "impossible" },
    { english: "asset", meanings: ["資産", "財産"], examples: ["Real estate is a valuable asset."], level: "medium" },
    { english: "annuity", meanings: ["年金", "年金保険"], examples: ["He invested in an annuity plan."], level: "hard" },
    { english: "synergy", meanings: ["相乗効果", "共同効果"], examples: ["The synergy between teams helped."], level: "medium" }
  ];
  